services:
  - type: web
    name: graphml-studio-gnn
    runtime: python
    plan: free
    rootDir: graphml-studio
    buildCommand: pip install -r requirements.txt
    startCommand: python gnn_services/app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: graphml-studio-web
    runtime: node
    plan: free
    rootDir: graphml-studio
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GNN_HOST
        fromService:
          name: graphml-studio-gnn
          type: web
          property: host
      - key: GNN_PORT
        fromService:
          name: graphml-studio-gnn
          type: web
          property: port
